name: Deploy to Pages

on:
  push:
    branches: ['main']
    paths-ignore: ['.md']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_URL: ${{ env.NEXT_PUBLIC_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Configure for Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
      - name: Run linter
        run: yarn lint
      - name: Run formatter
        run: yarn format:check
      - name: Build with Next.js
        run: yarn build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
